### ISSUE TITLE
Editor captures ctrl-f but does not provide a way to search

### ISSUE THREAD

**Issue by dnephin** [mdaines/viz-ui#1]
This was an issue with the v1.0 version as well, I assume it has to do with the ACE editor.

If I'm in the editor box and I hit `ctrl-f` to search for a term it grabs the keystroke. So instead of my browser "find on page" box opening nothing happens.

Do you know if there is an easy way to either turn that off, or provide the search functionality?

**Comment by mdaines** [comment]
Looks like the easiest thing to do is import the Ace search box extension. See cfea2486d2c42cc8bcfd191d055b7ea55189f357.

**Comment by dnephin** [comment]
Perfect!
